import * as React from 'react';
import { renderToString } from 'react-dom/server';
import { ServerStyleSheet } from 'styled-components';
import { App } from './index';
import { Navigation, getHistoryInfo } from './logic/navigation';
import { makeStores } from './store';
import { PageData } from './defs/page';
import { firebaseApp } from '../server/firebase';

export interface RenderResult {
  /**
   * Title of page.
   */
  title: string;
  /**
   * content HTML.
   */
  content: string;
  /** styles */
  styleTags: string;
  /**
   * page params.
   */
  params: Record<string, string>;
  /**
   * Page info for stores.
   */
  page: PageData | null;
  /**
   * Count store data.
   */
  count: number;
}
/**
 * Server-side rendering of requested page.
 */
export async function render(pathname: string): Promise<RenderResult> {
  // Initialize store for this rendering.
  const stores = makeStores();
  const runtime = {
    stores,
    firebase: firebaseApp,
  };
  // Simulate navigation to given path.
  const nav = new Navigation(runtime, true);
  await nav.move(pathname);
  // Prepare server-side rendering support by styled-components.
  const sheet = new ServerStyleSheet();
  const content = renderToString(sheet.collectStyles(<App stores={stores} />));
  // style tags generated by styled-components.
  const styleTags = sheet.getStyleTags();
  // destruct resources craeted by navigation.
  nav.close();
  const { params, page } = stores.page;
  if (page == null) {
    // TODO
    return {
      title: '404',
      content,
      styleTags,
      params,
      page,
      count: stores.counter.count,
    };
  }
  const { title } = getHistoryInfo(page);
  return {
    title,
    content,
    styleTags,
    params,
    page,
    count: stores.counter.count,
  };
}
