# Application server
server:
  port: 8080
  origin: "http://localhost:8080"
  # cache max-age of pages.
  cacheMaxAge: 3600
firebase: "firebase config here"
# Path to firebase service account key for admin SDK.
firebaseAdminKey: "path/to/key.json"
